# Generated by Django 3.1.1 on 2020-09-11 16:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crew',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('working_hours', models.CharField(max_length=30)),
                ('crew_members', models.CharField(max_length=30)),
                ('complains_id', models.CharField(max_length=330)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='infrastructure',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('google_location', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='id', unique=True)),
                ('made_afm', models.TextField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default='False')),
                ('notes', models.TextField(max_length=300)),
                ('resolve_date', models.DateTimeField()),
                ('infrastructure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.infrastructure')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
