# Generated by Django 3.1.1 on 2020-09-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='total_assigments',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
