# Generated by Django 3.1.1 on 2020-09-19 17:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_crew_total_assigments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='id',
        ),
        migrations.AlterField(
            model_name='complain',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='None', primary_key=True, serialize=False, unique=True),
        ),
    ]
