# Generated by Django 3.1.1 on 2020-09-19 17:54

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200919_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='slug_ref',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
