# Generated by Django 3.1.1 on 2020-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_crew_slug_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('done', models.BooleanField(default='False')),
            ],
            options={
                'ordering': ('-done',),
            },
        ),
    ]
